### ISSUE TITLE
Getting SRA reads for contig generation after magicBLAST

### ISSUE THREAD

**Issue by DCGenomics** [NCBI-Hackathons/EndoVir#1]
Leverage vdb-dump to pull the actual read accessions:  

https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?view=toolkit_doc&f=vdb-dump

**Comment by janpb** [comment]
Just figured how to get specific rows via sra-dump, (-R). Disregard corresponding rant in last commit (7a91056a58bdd66fc6f6fc1ba113c4c9eb3c3261).

**Comment by DCGenomics** [comment]
On the contrary, let's ask someone from toolkit team to watch these
issues.  If documentation is unclear to you, its very likely unclear to
others who aren't embedded.
