### ISSUE TITLE
Flag to accept fastq.gz files

### ISSUE THREAD

**Issue by DCGenomics** [NCBI-Hackathons/EndoVir#20]
Making magicblast accept fastq.gz files

**Comment by DCGenomics** [comment]
Just need a method alternate where 

https://github.com/NCBI-Hackathons/EndoVir/blob/master/lib/blast/magicblast/magicblast.py

Changes -sra to -query 

(a sensor would be better)

**Comment by DCGenomics** [comment]
Note: magicblast natively accepts fastq.gz files

**Comment by janpb** [comment]
fixed in dev branch. The magiclbast wrapper chekcs if hte sra is a file => -query or not -=> -sra
