### ISSUE TITLE
makeblastdb: local database and sequence retrieval ruckus

### ISSUE THREAD

**Issue by janpb** [NCBI-Hackathons/EndoVir#3]
Creating a local database using makeblastdb without Fasta ID \[0\]  results in unusable names for subsequent retrieval. Testing two options:

1. Format the input sequences using `>ref|Accsession|name`
2. Testing different blastdbcmd -outfmt options 

### References
[0](https://www.ncbi.nlm.nih.gov/toolkit/doc/book/ch_demo/#ch_demo.T5) https://www.ncbi.nlm.nih.gov/toolkit/doc/book/ch_demo/#ch_demo.T5

**Comment by DCGenomics** [comment]
Try -parseseqids

**Comment by boratyng** [comment]
It is -parse_seqids

**Comment by janpb** [comment]
Fixed. Thanks.
